### ISSUE TITLE
Handle probabilities (i.e. 1 in N chance effects)

### ISSUE THREAD

**Issue by kleinfreund** [kleinfreund/balatrolator#2]
## Description

Handle the various probabilistic effects of things like the "Bloodstone" joker, lucky enhanced cards, etc. Currently, they're not taken into account at all.

## Motivation

Some way to handle probabilities is definitely needed. Now I don't want to just roll the dice and have scores change based on whether, for example, a lucky card was triggered. I don't really have good ideas for this so far.

Some rough sketches:

- Show a worst case and best case score (this would be a decent "best effort" as probabilistic effects in Balatro are usually binary: they apply or they don't)
- Allow user to choose the result of the "dice rolls" (either on a global level (simpler) or per effect (more complicated))

**Jokers**:

Note that a lot of probabilistic jokers don't affect joker (e.g. Gros Michel)

- Bloodstone
- Oops! All 6s (meta)
- Misprint (random value instead of a binary dice roll)

**Modifiers**:

- Lucky enhancement

**Comment by EFHIII** [comment]
A range is what I went with for [my calculator](https://efhiii.github.io/balatro-calculator/?hand=oACMOJQACOMAECgAKag1BKA0BIA), but another feature that you might consider is showing the average scoring result which is probably more useful in cases where the range is very significant, for example:
[![image](https://github.com/kleinfreund/balatrolator/assets/20879009/d0d02cb5-3e24-497e-bcda-3bb0550ab348)](https://efhiii.github.io/balatro-calculator/?hand=oACMOJQACOMAECgAKag1BKA0BIA)

**Comment by EFHIII** [comment]
I now show a mean and median in [mine](https://efhiii.github.io/balatro-calculator/?hand=oACMOJQACOMAECgAKag1BKA0BIA&h=oACMHEoAAjhgAQFAAU1BqCUBoCQ):
![image](https://github.com/kleinfreund/balatrolator/assets/20879009/8e4a3788-a451-4a51-8491-643d20e1d84f)

**Comment by kleinfreund** [comment]
I've added handling of probabilities in https://github.com/kleinfreund/balatrolator/commit/a5b71896573120b70ce240a5c88b1b189d4b0624. I went with the following approach:

The calculator now determines the score using three different luck "modes": no luck (i.e. the lowest score possible), average luck, and all luck (i.e. the highest score possible).

"No luck" means no probabilistic effects are activated. This represents the lowest possible score one can get. This "mode" effectively behaves as the calculator did before this change: lucky cards, Bloodstone, and Oops! All 6s don't (and didn't) increase the score.

"All luck" is the other extreme: all probabilistic effects are always activated and they always have the best possible effect (lucky cards always add their +Mult, Bloodstone always triggers, and Misprint always adds its highest +Mult).

"Average luck" tries to produce a more or less expected score value. Instead of actually rolling any dice (which would produce different values every time), the probabilistic effects/values are averaged during scoring:

- Lucky Cards: 4 +Mult (representing the 1 in 5 chance by dividing the enhancement's 20 +Mult by 5)
- Misprint: 11.5 +Mult (the average of the 0 to 23 +Mult range of the joker)
- Bloodstone: 4/3 xMult (representing the 1 in 3 chance of triggering a 2 xMult by instead always applying a 1.333 xMult)

Oops! All 6s doubles these effects (Lucky: 8 +Mult; Misprint: 11.5 +Mult, i.e. the same as it's not a 1 in N chance probability; Bloodstone: 5/3 xMult). I'm not totally sure, but I think one can't copy the Oops! All 6s effect, but I would need to check that.

**Comment by EFHIII** [comment]
You can't blueprint/brainstorm Oops! All 6s but you can have multiple of them and the effect stacks up to 100% chance.

Is there a reason not to the show the result of all modes at once (only when they're not all the same)?

Also, if Oops! All 6s makes the chance 100%, that probably aught to be reflected in the lower bound.

**Comment by kleinfreund** [comment]
> Also, if Oops! All 6s makes the chance 100%, that probably aught to be reflected in the lower bound.

Good call. In my first iteration I wasn't handling multiple Oops! All 6s and consequently didn't bother "raising" the lower bound if your jokers make you chances guarantees (like 2x Oops! All 6s would for Bloodstone). I fixed that now. Works for both Bloodstone and lucky cards (however unlikely that is in practice).



> Is there a reason not to the show the result of all modes at once (only when they're not all the same)?

It's somewhat arbitrary, but I don't see a strong reason to show the three results if they're the same anyway.
