### ISSUE TITLE
Shorter state URLs

### ISSUE THREAD

**Issue by EFHIII** [kleinfreund/balatrolator#7]
Right now, the state URLs are very long; for example:
https://balatrolator.com/?state=N4IgFghgdgJgziAXARgDQhgSzgYwgJ3iQAZ0BbAeygFMBPE9AIwBtNYlQoIzqkQBlMhGbMABACFW7dNgCCOAC6YAbr0QL8AV2oBfdDGo4A1nwBK1GKIAihk%2BkiwAMtVXMEiUADFmmuGFGeKmqgzC7UzEhoIAAOzBC07sR6IN6%2B-gASFL7BIKGukeix8YnJgaqiFABmohCiANJsMBy5YREohXEJJMn8GhCYAOZgCgE%2Bfs154QUxnSXonln4FdW1DeweLfntM8Xd85oiopnZE63TRV2ISfNjYKdbACwdu1c9fYPD91PbF3MgACpgfDUajLGr1RpfNpRX57AEAdwoogACv18FDzrM4ajMOiNpNoc9LtcQOkPqIAMIEJr4s4-LGvZIAKwoRmo%2BHcAG1ONw1AIKMYarAJL4jGwQOgLJglFQ%2BIwIHBeB1fBSwJhoollXAALIHJSxTDshggJQ8HV69WsI3bfDQEyIEDyJUgOCaaV8Ck%2BRgIGRweRKVRIDTaPQ8nh8KyiiUgKUyqByhXO2IqtUa43J83MfVWvGkE2YM26rOWw14qK2qD2x04Z2u90Oz2ab3RuSKIJBrS6VBhvmOXwKWiiABSrKNkqwcYTiujGdV6s1M18RezpeNpuomZX1vLdr4TujdYUHq9PpArYDamDXZ7fEk2mi%2BDYR-H0swsod8unWrnaauWuXJbWnm66boBZYAEwAHTgQArOgFZVvu6CHseTanue7bqJ2oYgFw4YOpIFAUPAChUM6sZvvGH6JjOYw-guGYAQaQHoCBTE5tMCF7jWB5ukeDYni2fptoGWEhgAuugLJsvg-DMBQCjuAAbESFhUoQXKgFxDprAMvH1qS1AEIp0YUe%2BICfuRUAODWPBQPxuFkQeRltI5NBCTYjCaJUlQWEglTCIqOHaSAun6Q56RGfgJkvpO1FfjG1nQLZ1D2XwUBOchLnpZlZ5wJ53m%2BTSAVuNeIAhUOEDGOFfCRcZp5mVRFk0ZKSVQClaUOhl7lZcIOU9XlBU%2BX5iAlUF3blbuDpIS6fG1VFMUxhOlFTlZNnUHZDndbW2Vdbl2BDUV-mBWVIVKTVDp1dFDXLeZlmmW1HVbblip9XtA0HdQXnDcVJ06JJ4DhDA6lEIgnLiToQA

I know you're tracking a few more things than I am, but the same hand in my calculator has a URL state-string that's less than 3% of the length of yours:
https://efhiii.github.io/balatro-calculator/?hand=oACMOJQACOMAECgAKaA0BIAwBA

There are a few things that made it possible for me to make the state-string so short:
- default states:
  - If a particular feature isn't used, it can be represented using only 1 bit to signify that it's in the default state; for example:
      - hand level (default each to 1)
      - joker state (default to the state it's at when bought)
- minimal bit-lengths for values; for example:
  - edition: 1 bit to signify if it's standard, if non-standard, 2 bits for which edition (my 4 states don't include negative but does include disabled)
  - enhancement: 3 bits for which enhancement and 1 bit for if it has a Red (Double) Tag (other tags are not bothered with)
  - joker type: 8 bits
  - number for suit: 2 bits
  - number for card type (2 - ace): 4 bits
  - most numbers are stored as either 16 bit unsigned int or 16 bit signed int
    - number of cards is a 16 bit unsigned int
    - number of jokers is a 16 bit unsigned int
    - hand levels are 16 bit unsigned ints
    - joker states are 16 bit signed ints
- assumed 0s
  - the representation of all default values is via 0s and the last step in my URL building function is to remove trailing zeros, then during URL interpreting, I assume any bits past what was provided in the URL is a zero.
  - Ordering less-used features (like number of planets in the consumable area for Observatory) at the end so that they usually are free because of assumed 0s
  
  Even if you don't want to rely on using small numbers like 16 bit ints, you can use small ints where possible and have a higher bit-length fallback, but for all the things I used 16 bit ints for, I don't think it's practical for the integer limit to be reached.

**Comment by kleinfreund** [comment]
Thanks for the suggestion, @EFHIII!

I've implemented a more application-specific (custom) algorithm for shorter share URLs in https://github.com/kleinfreund/balatrolator/commit/c114663f4cffa68c2db4817b25a2db06558f3734.

This is possibly not final and certainly not the most minimal in terms of URL length, but much better than the previous URLs which were indeed excessive. I want to give myself some room in case the state model I use needs significant changes (pretty much certain at this stage of development). I want to avoid needing to change it too often because every time I do, the chance the current URLs break is very high.

**Comment by EFHIII** [comment]
I think it's broken at the moment

**Comment by kleinfreund** [comment]
> I think it's broken at the moment

Could you be a bit more specific, please? I can look at this later, but from a quick glance, it seems to work. Note that any previous URLs will definitely be broken. I very much consider this project a work-in-progress in the current stage and am fine with breaking things like that if necessary.

**Comment by EFHIII** [comment]
Sorry, I was messing with it and every time I refreshed, it went back to blank. I hadn't realized you had to click the submit button to get the url to update.
(the URL on mine updates anytime something changes)
